package br.com.fiap.projeto_redepapagaio.model;

public enum TipoOcorrenciaEnum {
	INUNDACAO, ALAGAMENTO, ENXURRADA, ENCHENTE, DESLIZAMENTO, TERREMOTO, ERUPCAO_VULCANICA, ONDA_CALOR, ONDA_FRIO, CICLONE, TORNADO, TEMPESTADE_SEVERA, SECA_PROLONGADA, INCENDIO_FLORESTAL
}
